// <auto-generated />
using System;
using shcome.loxone.sensor.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace shcome.loxone.sensor.Migrations
{
    [DbContext(typeof(SeonsorAppDbContext))]
    [Migration("20220403193753_IntlCreate")]
    partial class IntlCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("shcome.loxone.sensor.EntityObjects.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Category")
                        .HasColumnType("character varying")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Room")
                        .HasColumnType("character varying")
                        .HasColumnName("room");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("sensor", "public");
                });

            modelBuilder.Entity("shcome.loxone.sensor.EntityObjects.SensorValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descriminator")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("descriminator");

                    b.Property<double?>("Reading")
                        .HasColumnType("double precision")
                        .HasColumnName("reading");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensorId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("sensor_value", "public");
                });

            modelBuilder.Entity("shcome.loxone.sensor.EntityObjects.SensorValue", b =>
                {
                    b.HasOne("shcome.loxone.sensor.EntityObjects.Sensor", "Sensor")
                        .WithMany("SensorValues")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("shcome.loxone.sensor.EntityObjects.Sensor", b =>
                {
                    b.Navigation("SensorValues");
                });
#pragma warning restore 612, 618
        }
    }
}
